name: Deploy

on:
  push:
    branches:
      - staging # Staging (development) branch
      - main    # Production branch

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3

      # Step 3: Install Dependencies
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      # Step 4: Run Linter (ESLint)
      - name: Run ESLint
        run: npx eslint .
        continue-on-error: false # Halt pipeline on lint errors

      # Step 5: Run Tests
      - name: Run Tests
        run: npm test

      # Step 6: Build the Project
      - name: Build project
        run: npm run build

      # Step 7: Upload Build Artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./dist

  deploy:
    name: Deploy
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ${{ github.ref == 'refs/heads/main' && '' || 'staging' }}